### ISSUE TITLE
Todo App 요구사항 명세서 작성

### ISSUE THREAD

**Issue by SJUANS** [SJUANS/toDoAppTutorial#1]
### 만들고자 하는 기능이 무엇인가요? 
-> Todo 생성 기능(21일까지는 문자열 출력 API 응답 + 할일 등록 기능까지 구현)

### 해당 기능을 구현하기 위해 할 일이 무엇인가요?

- [x] intelliJ로 Spring Boot 템플릿 프로젝트 생성

### 아래 파일을 포함합니다.

- [x] README.md

- [x] .gitignore

- [x] LICENSE

### Github Project 칸반

- [x]  Todo App을 직접 만든다고 생각하고 이슈, 마일스톤을 스스로 정해봅니다.

- [x] Github Project 칸반을 만들고, 이슈와 마일스톤을 연결하고 칸반 뷰로 변경합니다

### Coz’ Git flow

- [x] 직접 제작한 Github 리포지토리에 main, dev 브랜치를 만듭니다.

- [x] dev 브랜치에서 main 브랜치로 Pull Request를 최소 1회 시도합니다.

       
- [x] 신규 프로젝트를 생성하고 ‘To-do Application !’라는 문자열을 출력할 수 있는 간단한 API를 만들고, 원격 main 브랜치로 push 합니다.

- [x]  ‘To-do Application !’라는 문자열을 응답할 수 있는 개발 서버와 IDE가 켜져있는 화면을 캡쳐합니다.

### 예상 작업 시간
6h
